### ISSUE TITLE
生成的文档为空

### ISSUE THREAD

**Issue by LL1024LL** [gotomicro/ego-gen-api#11]
我们api目录下放的都是controller相关代码，用gin框架解析参数之类的，执行的命令
```
egogen --output docs2 --plugin gin --dir api
```

docs2目录中生成的swagger.json内容：
```
{
    "swagger": "2.0",
    "info": {},
    "paths": {}
}
```

没有日志输出，请问该如何排查呢？感谢

**Comment by link-duan** [comment]
已于 `v0.0.1-rc3` 版本修复，请安装新版本尝试 `go install github.com/gotomicro/ego-gen-api/cmd/egogen@v0.0.1-rc3`

**Comment by link-duan** [comment]
fixed
